var user = 
{
  "A Sravanthi": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "News-No, none of the below-Absolutely Certain"
  ],
  "Abdul Aleen": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Adult product/service (explicit sale of)-Absolutely Certain"
  ],
  "Afsha Tahseen": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Anusha Regulagadda": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "News-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain"
  ],
  "ARDHI DEEPAK RAO": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Ashwini Gandla": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain"
  ],
  "Ashwini Sneha": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain"
  ],
  "B Rama kanth": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Entertainment/gaming-Profanity-Swearwords related to sex (ex: f**k-motherf*cker-etc)-5 or more-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Idealized Body-Pinching-circling-pointing out defect-Absolutely Certain"
  ],
  "Bhanu Kalahasti": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain"
  ],
  "Bhargav Varma Chinda": [
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "News-No, none of the below-Absolutely Certain"
  ],
  "Brahmendra Tanneeru": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain"
  ],
  "Chandan Kumar S": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "News-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Deepika G": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Farha Nausheen": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Girimalla Kathyaini": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Girish Supriya": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Botox-No, none of the below-Absolutely Certain",
    "News-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain"
  ],
  "Goutham Chennamadhavuni": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain"
  ],
  "Jadali Sushmita": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain"
  ],
  "K Ramu": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "K Saraswathi": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain"
  ],
  "Keerthi Jyothi": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain"
  ],
  "Manikantareddy Reddy": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "News-No, none of the below-Absolutely Certain"
  ],
  "manohar soodula": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain"
  ],
  "Mirza Hameed Baig": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Idealized Body-Repeated before & after-Absolutely Certain"
  ],
  "Mohammed Uzair": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Procedures involving lasers-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "Mouna Priya": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Idealized Body-Pinching-circling-pointing out defect-Absolutely Certain"
  ],
  "Naresh K": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain"
  ],
  "Ninny Gidda": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Nithin Chepyala": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "Pooja Thakur": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Prajwal Ganji": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "Prashanth Buyankar": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Praveen Potharaveni": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Specifically whitening cream-No, none of the below-Absolutely Certain"
  ],
  "Preethi D": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "Pruthvi Krishna": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Ravi Kunchala": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Rebekah Lawrence": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain"
  ],
  "Reena Summera": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "Sai Priya Vinder": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "Sai Sharan Chandra Macharla": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Procedures involving lasers-No, none of the below-Absolutely Certain"
  ],
  "Sangeetha EM": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Shashidhar Maru": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain"
  ],
  "Shikha Rani Upadhyay": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "Simon Patakula": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Soni Khatun": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Idealized Body-Repeated before & after-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "sreedhar Gangakhedkar": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Swetha Kandhada": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Idealized Body-Repeated before & after-Absolutely Certain"
  ],
  "SyedMeesum Hussain Razvi": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Surgery-No, none of the below-Absolutely Certain"
  ],
  "VamshiRaju Dappu": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain"
  ],
  "Vineeth Madiraju": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Language-Physical or Mental health attribute-Assertion-Weight-loss-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-Idealized Body-Repeated before & after-Absolutely Certain"
  ],
  "Vinu Anthony": [
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Alcohol (explicit sale of)-None of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Clinic non-surgical services (ex: dental non-surgery)-No, none of the below-Absolutely Certain",
    "None of the products/services below-Profanity-Absolutely Certain"
  ],
  "VIshal Tiwari": [
    "Entertainment/gaming-None of the policies below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Incorrect \"f\" Logo-No-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Adult Health (explicit sale of)-Explicit Diet/Weight Loss Product or Service-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Cosmetic services (ex: waxing)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Non-ingestible treatments (ex: topical cream)-No, none of the below-Absolutely Certain",
    "Non-Adult Health Physical Improvement (explicit sale of)-Specifically whitening cream-No, none of the below-Absolutely Certain",
    "None of the products/services below-Facebook Reference-Thumbs Up Icon-No-Absolutely Certain"
  ]
};